
PUT http://localhost:8080/guzzler/start
Accept: */*
Content-Type: application/json

###

PUT http://localhost:8080/guzzler/stop
Accept: */*
Content-Type: application/json

###

PUT http://localhost:8080/shutdown
Accept: */*
Content-Type: application/json

###

PUT http://localhost:8080/profiling/start
Accept: */*
Content-Type: application/json

###

PUT http://localhost:8080/profiling/stop
Accept: */*
Content-Type: application/json

###

POST http://localhost:8080/auctions
Accept: */*
Content-Type: application/json

{
  "productTitle": "MacBook Pro",
  "productDescription": "An awesome thing to work with.",
  "secondsToRun": 500
}

> {%
  client.global.set("uuid", response.body.uuid);
  client.log(client.global.get("uuid"));
%}


###

GET http://localhost:8080/auctions/{{uuid}}
Accept: */*
Content-Type: application/json

> {%
  client.global.set("highestBid", response.body.highestBid.amount);
  client.global.set("next", response.body.highestBid.amount+1);
  client.log(client.global.get("highestBid"));
%}


###

PUT http://localhost:8080/auctions/{{uuid}}
Accept: */*
Content-Type: application/json

{
  "email": "bieter@crowdcode.io",
  "amount": {{next}}
}

###

GET http://localhost:8080/auctions?search=BOOK
Accept: */*
Content-Type: application/json

###

